export const testGenres = [
    { _id: "Drama", count: "" },
    { _id: "Comedy", count: "" },
    { _id: "Romance", count: "" },
    { _id: "Crime", count: "" },
    { _id: "Thriller", count: "" },
    { _id: "Action", count: "" },
    { _id: "Documentary", count: "" },
    { _id: "Adventure", count: "" },
    { _id: "Horror", count: "" },
    { _id: "Biography", count: "" },
];

export const testCountries = [
    { _id: "Australia" },
    { _id: "Austria" },
    { _id: "Belgium" },
    { _id: "China" },
    { _id: "Denmark" },
    { _id: "Finland" },
    { _id: "France" },
    { _id: "Germany" },
    { _id: "Hong Kong" },
    { _id: "Israel" },
    { _id: "Italy" },
    { _id: "Japan" },
    { _id: "Mexico" },
    { _id: "New Zealand" },
    { _id: "Norway" },
    { _id: "Poland" },
    { _id: "Romania" },
    { _id: "Russia" },
    { _id: "Spain" },
    { _id: "Sweden" },
    { _id: "Switzerland" },
    { _id: "Taiwan" },
    { _id: "UK" },
    { _id: "USA" },
];
